package container

import (
	"github.com/Aether-v1/hcz/internal/authz"
	"github.com/Aether-v1/hcz/internal/config"
	adproxyapp "github.com/Aether-v1/hcz/internal/modules/adproxy/application"
	affiliateapp "github.com/Aether-v1/hcz/internal/modules/affiliate/application"
	affiliatecontract "github.com/Aether-v1/hcz/internal/modules/affiliate/contract"
	apicredentialapp "github.com/Aether-v1/hcz/internal/modules/apicredential/application"
	apicredentialcontract "github.com/Aether-v1/hcz/internal/modules/apicredential/contract"
	auditlogapp "github.com/Aether-v1/hcz/internal/modules/auditlog/application"
	auditlogcontract "github.com/Aether-v1/hcz/internal/modules/auditlog/contract"
	c2capp "github.com/Aether-v1/hcz/internal/modules/c2c/application"
	c2cgormstore "github.com/Aether-v1/hcz/internal/modules/c2c/infrastructure/gormstore"
	captchaapp "github.com/Aether-v1/hcz/internal/modules/captcha/application"
	cardsecretapp "github.com/Aether-v1/hcz/internal/modules/cardsecret/application"
	cardsecretgormstore "github.com/Aether-v1/hcz/internal/modules/cardsecret/infrastructure/gormstore"
	cartapp "github.com/Aether-v1/hcz/internal/modules/cart/application"
	cartgormstore "github.com/Aether-v1/hcz/internal/modules/cart/infrastructure/gormstore"
	categoryapp "github.com/Aether-v1/hcz/internal/modules/catalog/category/application"
	categorycontract "github.com/Aether-v1/hcz/internal/modules/catalog/category/contract"
	mappingapp "github.com/Aether-v1/hcz/internal/modules/catalog/mapping/application"
	mappinggormstore "github.com/Aether-v1/hcz/internal/modules/catalog/mapping/infrastructure/gormstore"
	productapplication "github.com/Aether-v1/hcz/internal/modules/catalog/product/application"
	productadmin "github.com/Aether-v1/hcz/internal/modules/catalog/product/application/admin"
	productwrite "github.com/Aether-v1/hcz/internal/modules/catalog/product/application/write"
	productgormstore "github.com/Aether-v1/hcz/internal/modules/catalog/product/store/gormstore"
	channelclientapp "github.com/Aether-v1/hcz/internal/modules/channelclient/application"
	channelclientcontract "github.com/Aether-v1/hcz/internal/modules/channelclient/contract"
	complianceapp "github.com/Aether-v1/hcz/internal/modules/compliance/application"
	contentapp "github.com/Aether-v1/hcz/internal/modules/content/application"
	couponapp "github.com/Aether-v1/hcz/internal/modules/coupon/application"
	coupongormstore "github.com/Aether-v1/hcz/internal/modules/coupon/infrastructure/gormstore"
	dashboardapp "github.com/Aether-v1/hcz/internal/modules/dashboard/application"
	dashboardcontract "github.com/Aether-v1/hcz/internal/modules/dashboard/contract"
	downstreamcallbackapp "github.com/Aether-v1/hcz/internal/modules/downstreamcallback/application"
	downstreamcallbackcontract "github.com/Aether-v1/hcz/internal/modules/downstreamcallback/contract"
	exchangerateapp "github.com/Aether-v1/hcz/internal/modules/exchangerate/application"
	fulfillmentapp "github.com/Aether-v1/hcz/internal/modules/fulfillment/application"
	fulfillmentcontract "github.com/Aether-v1/hcz/internal/modules/fulfillment/contract"
	giftcardapp "github.com/Aether-v1/hcz/internal/modules/giftcard/application"
	giftcardgormstore "github.com/Aether-v1/hcz/internal/modules/giftcard/infrastructure/gormstore"
	admincontract "github.com/Aether-v1/hcz/internal/modules/identity/admin/contract"
	adminauthapp "github.com/Aether-v1/hcz/internal/modules/identity/adminauth/application"
	admintotpapp "github.com/Aether-v1/hcz/internal/modules/identity/adminauth/totp/application"
	emailverificationcontract "github.com/Aether-v1/hcz/internal/modules/identity/emailverification/contract"
	externalidentitycontract "github.com/Aether-v1/hcz/internal/modules/identity/externalidentity/contract"
	googleauthapp "github.com/Aether-v1/hcz/internal/modules/identity/googleauth/application"
	telegramauthapp "github.com/Aether-v1/hcz/internal/modules/identity/telegramauth/application"
	usercontract "github.com/Aether-v1/hcz/internal/modules/identity/user/contract"
	userauthapp "github.com/Aether-v1/hcz/internal/modules/identity/userauth/application"
	usertotpapp "github.com/Aether-v1/hcz/internal/modules/identity/userauth/totp/application"
	memberlevelapp "github.com/Aether-v1/hcz/internal/modules/memberlevel/application"
	memberlevelcontract "github.com/Aether-v1/hcz/internal/modules/memberlevel/contract"
	memberlevelgormstore "github.com/Aether-v1/hcz/internal/modules/memberlevel/infrastructure/gormstore"
	notificationapp "github.com/Aether-v1/hcz/internal/modules/notification/application"
	notificationgormstore "github.com/Aether-v1/hcz/internal/modules/notification/infrastructure/gormstore"
	notificationsmtp "github.com/Aether-v1/hcz/internal/modules/notification/infrastructure/smtp"
	orderapp "github.com/Aether-v1/hcz/internal/modules/order/application"
	"github.com/Aether-v1/hcz/internal/modules/order/application/aftersale"
	orderrefund "github.com/Aether-v1/hcz/internal/modules/order/application/refund"
	ordercontract "github.com/Aether-v1/hcz/internal/modules/order/contract"
	orderriskapp "github.com/Aether-v1/hcz/internal/modules/orderrisk/application"
	paymentapp "github.com/Aether-v1/hcz/internal/modules/payment/application"
	paymentcontract "github.com/Aether-v1/hcz/internal/modules/payment/contract"
	paymentprovider "github.com/Aether-v1/hcz/internal/modules/payment/infrastructure/gateway/provider"
	procurementapp "github.com/Aether-v1/hcz/internal/modules/procurement/application"
	procurementgormstore "github.com/Aether-v1/hcz/internal/modules/procurement/infrastructure/gormstore"
	promotionapp "github.com/Aether-v1/hcz/internal/modules/promotion/application"
	promotiongormstore "github.com/Aether-v1/hcz/internal/modules/promotion/infrastructure/gormstore"
	reconciliationapp "github.com/Aether-v1/hcz/internal/modules/reconciliation/application"
	reconciliationcontract "github.com/Aether-v1/hcz/internal/modules/reconciliation/contract"
	reseller "github.com/Aether-v1/hcz/internal/modules/reseller/application"
	resellergormstore "github.com/Aether-v1/hcz/internal/modules/reseller/infrastructure/gormstore"
	settingsapp "github.com/Aether-v1/hcz/internal/modules/settings/application"
	settingscontract "github.com/Aether-v1/hcz/internal/modules/settings/contract"
	siteconnectionapp "github.com/Aether-v1/hcz/internal/modules/siteconnection/application"
	siteconnectioncontract "github.com/Aether-v1/hcz/internal/modules/siteconnection/contract"
	sitemapapp "github.com/Aether-v1/hcz/internal/modules/sitemap/application"
	broadcastapp "github.com/Aether-v1/hcz/internal/modules/telegram/broadcast/application"
	broadcastcontract "github.com/Aether-v1/hcz/internal/modules/telegram/broadcast/contract"
	uploadapp "github.com/Aether-v1/hcz/internal/modules/upload/application"
	usernotificationapp "github.com/Aether-v1/hcz/internal/modules/usernotification/application"
	usernotificationgormstore "github.com/Aether-v1/hcz/internal/modules/usernotification/infrastructure/gormstore"
	walletapp "github.com/Aether-v1/hcz/internal/modules/wallet/application"
	walletgormstore "github.com/Aether-v1/hcz/internal/modules/wallet/infrastructure/gormstore"
	withdrawalapp "github.com/Aether-v1/hcz/internal/modules/walletwithdrawal/application"
	withdrawalgormstore "github.com/Aether-v1/hcz/internal/modules/walletwithdrawal/infrastructure/gormstore"
	"github.com/Aether-v1/hcz/internal/queue"
	"github.com/Aether-v1/hcz/internal/shared/mailbrand"
)

// Container 声明应用运行期共享的依赖表面；具体构造过程按职责拆分在同包装配文件中。
type Container struct {
	Config      *config.Config
	QueueClient *queue.Client

	// Repositories
	AdminStore             admincontract.Store
	UserStore              usercontract.Store
	ExternalIdentityStore  externalidentitycontract.Store
	EmailVerificationStore emailverificationcontract.Store
	OrderStore             ordercontract.Store
	PaymentStore           paymentcontract.Store
	PaymentChannelStore    paymentcontract.ChannelStore
	CardSecretRepo         *cardsecretgormstore.Store
	CardSecretBatchRepo    *cardsecretgormstore.BatchStore
	GiftCardRepo           *giftcardgormstore.Store
	FulfillmentStore       fulfillmentcontract.Store
	ProductRepo            *productgormstore.ProductStore
	ProductSKURepo         *productgormstore.SKUStore
	CartRepo               *cartgormstore.Store
	CouponRepo             *coupongormstore.Store
	CouponUsageRepo        *coupongormstore.UsageStore
	PromotionRepo          *promotiongormstore.Store
	WalletRepo             *walletgormstore.Store
	WithdrawalRepo         *withdrawalgormstore.Store
	C2CRepo                *c2cgormstore.Store
	CategoryRepo           categorycontract.Repository
	SettingRepo            settingscontract.Store
	UserLoginLogRepo       auditlogcontract.UserLoginRepository
	AuthzAuditLogRepo      auditlogcontract.AuthzRepository
	NotificationLogRepo    *notificationgormstore.LogStore
	AdminLoginLogRepo      auditlogcontract.AdminLoginRepository
	DashboardRepo          dashboardcontract.Repository
	AffiliateRepo          affiliatecontract.Store
	ResellerStore          *resellergormstore.Store
	ApiCredentialRepo      apicredentialcontract.Repository
	SiteConnectionRepo     siteconnectioncontract.Repository
	ProductMappingRepo     *mappinggormstore.MappingStore
	SKUMappingRepo         *mappinggormstore.SKUMappingStore
	ProcurementOrderRepo   *procurementgormstore.Store
	DownstreamOrderRefRepo downstreamcallbackcontract.Repository
	ReconciliationJobRepo  reconciliationcontract.JobRepository
	ReconciliationItemRepo reconciliationcontract.ItemRepository
	ChannelClientStore     channelclientcontract.Store
	TelegramBroadcastRepo  broadcastcontract.Store
	MemberLevelRepo        memberlevelcontract.LevelRepository
	MemberLevelPriceRepo   *memberlevelgormstore.PriceStore
	MemberLevelUserRepo    memberlevelcontract.UserRepository
	UserNotificationRepo   *usernotificationgormstore.Store

	// Services
	AuthzService                  *authz.Service
	AuthService                   *adminauthapp.Service
	TOTPService                   *admintotpapp.Service
	UserTOTPService               *usertotpapp.Service
	UserAuthService               *userauthapp.Service
	TelegramAuthService           *telegramauthapp.Service
	GoogleAuthService             *googleauthapp.Service
	EmailSender                   *notificationsmtp.Service
	EmailBrandResolver            mailbrand.Resolver
	CaptchaService                *captchaapp.Service
	UploadService                 *uploadapp.Service
	ProductReadService            *productapplication.Service
	ProductAdminService           *productadmin.AdminService
	ProductWriteService           *productwrite.WriteService
	ContentPostService            *contentapp.PostService
	ContentPostCategoryService    *contentapp.PostCategoryService
	ContentBannerService          *contentapp.BannerService
	ContentMediaService           *contentapp.MediaService
	CategoryService               *categoryapp.Service
	SettingService                *settingsapp.Service
	SitemapService                *sitemapapp.Service
	ExchangeRateService           *exchangerateapp.Service
	CartService                   *cartapp.Service
	WalletService                 *walletapp.Service
	WithdrawalService             *withdrawalapp.Service
	C2CService                    *c2capp.Service
	OrderRefundService            *orderrefund.Service
	AfterSaleService              *aftersale.Service
	OrderService                  *orderapp.OrderService
	FulfillmentService            *fulfillmentapp.Service
	CouponAdminService            *couponapp.AdminService
	PromotionAdminService         *promotionapp.AdminService
	PaymentService                *paymentapp.PaymentService
	CardSecretService             *cardsecretapp.Service
	GiftCardService               *giftcardapp.Service
	UserLoginLogService           *auditlogapp.UserLoginService
	AuthzAuditService             *auditlogapp.AuthzService
	AdminLoginLogService          *auditlogapp.AdminLoginService
	NotificationLogService        *notificationapp.LogService
	DashboardService              *dashboardapp.Service
	NotificationService           *notificationapp.Service
	AffiliateService              *affiliateapp.Service
	ResellerDomainResolver        *reseller.DomainResolver
	ResellerPricingResolver       *orderapp.ResellerPricingResolver
	ResellerManagementService     *reseller.ManagementService
	ResellerSiteConfigService     *reseller.SiteConfigService
	ResellerProductSettingService *reseller.ProductSettingService
	ResellerAccountingQuery       *reseller.AccountingQueryService
	ResellerAccountingWithdraw    *reseller.AccountingWithdrawService
	ResellerAccountingLedger      *reseller.AccountingLedgerService
	ResellerOrderService          *reseller.OrderQueryService
	ResellerOperationsService     *reseller.OperationsService
	ApiCredentialService          *apicredentialapp.Service
	SiteConnectionService         *siteconnectionapp.Service
	ProductMappingService         *mappingapp.Service
	ProcurementOrderService       *procurementapp.Service
	DownstreamCallbackService     *downstreamcallbackapp.Service
	ReconciliationService         *reconciliationapp.Service
	ChannelClientService          *channelclientapp.Service
	TelegramBroadcastService      *broadcastapp.Service
	MemberLevelService            *memberlevelapp.Service
	AdProxyService                *adproxyapp.Service
	OrderRiskControlService       *orderriskapp.Service
	ComplianceService             *complianceapp.Service
	UserNotificationService       *usernotificationapp.Service

	PaymentProviderRegistry *paymentprovider.Registry
}
